language: python
python:
  - 2.7
  - "2.7_with_system_site_packages"
  - 3.4
install: 
  - pip install -r requirements.txt
  - pip install python-coveralls
script:
  - nosetests --with-coverage --cover-package=ads
after_success:
  coveralls
notifications:
  email: false
